apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visign-dev
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/LyyHua/visign-llmates
    targetRevision: HEAD
    path: k8s-specifications/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: visign-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true