apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visign-web-dev
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://github.com/LyyHua/visign-llmates
    targetRevision: dev
    path: k8s-specifications/overlays/dev/visign-web
  destination:
    server: https://kubernetes.default.svc
    namespace: visign-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
