apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visign-web-prod
  namespace: argocd
spec:
  project: prod-project
  source:
    repoURL: https://github.com/LyyHua/visign-llmates
    targetRevision: main
    path: k8s-specifications/overlays/prod/visign-web
  destination:
    server: https://kubernetes.default.svc
    namespace: visign-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
