apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Shared cluster-scoped infrastructure resources
  sourceRepos:
    - 'https://github.com/LyyHua/visign-llmates'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
