apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appprojects/dev.yaml
  - appprojects/prod.yaml
  - appprojects/infra.yaml
  - appsets/services.yaml
  - appsets/infra-nonprod.yaml
  - appsets/infra-prod.yaml
  - rbac-cm.yaml
