apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appproject-dev.yaml
  - appproject-prod.yaml
  - appproject-infra.yaml
  - application-visign-dev.yaml
  - application-visign-prod.yaml
  - application-visign-infra.yaml
