apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:dev-access, applications, get, dev-project/*, allow
    p, role:dev-access, applications, sync, dev-project/*, allow
    p, role:prod-access, applications, get, prod-project/*, allow
    p, role:prod-access, applications, sync, prod-project/*, allow
    p, role:sub-admin, applications, *, */*, allow
    g, developers, role:dev-access
    g, sub-admins, role:sub-admin