apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visign-dev
labels:
  - pairs:
      app.kubernetes.io/name: visign-web
      app.kubernetes.io/instance: dev
      app.kubernetes.io/component: web
    includeSelectors: false
resources:
  - ../../../base/visign-web
components:
  - ../shared
patches:
  - target:
      kind: Ingress
      name: visign-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.lyhua.dpdns.org
      - op: replace
        path: /spec/tls/0/secretName
        value: visign-tls-dev
      - op: replace
        path: /spec/rules/0/host
        value: dev.lyhua.dpdns.org
  - target:
      kind: Deployment
      name: visign-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: visign-web
    newName: visignnonprodacrzse7xf.azurecr.io/visign-web
    newTag: "dev-2ca9a41f23bace57a1ba4f22b8dcced757ef4ba7"
