apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: visign-dev

commonLabels:
  app.kubernetes.io/name: visign-web
  app.kubernetes.io/instance: dev
  app.kubernetes.io/component: web

resources:
  - ../../../base

components:
  - ../shared

patches:
  - target:
      kind: Deployment
      name: visign-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: visign-web
    newName: visignnonprodacrzse7xf.azurecr.io/visign-web
    newTag: "dev-fcaf670e118e36d9481f09fca949c615d82d4e70"
