apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visign-prod
resources:
  - ../base
  - secrets-provider.yaml
  - ingress.yaml
images:
  - name: visignacrftll4r7kkywwy.azurecr.io/visign-ai
    newName: visignpacrftll4r7kkywwy.azurecr.io/visign-ai
    newTag: ""
  - name: visignacrftll4r7kkywwy.azurecr.io/visign-web
    newName: visignpacrftll4r7kkywwy.azurecr.io/visign-web
    newTag: main-8dd8320d02f8509ba90e5f26fef06e8511a3e911
