apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: visign-kv-secrets
  namespace: visign-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "__DYNAMIC__"
    keyvaultName: "__DYNAMIC__"
    cloudName: ""
  objects: |
    array:
    - |
      objectName: DATABASE-URL
      objectType: secret
    - |
      objectName: CLERK-PUBLISHABLE-KEY
      objectType: secret
    - |
      objectName: CLERK-SECRET-KEY
      objectType: secret
    - |
      objectName: OPENAI-API-KEY
      objectType: secret
    - |
      objectName: TORCH-COMPUTE
      objectType: secret
    tenantId: "__DYNAMIC__"
  secretObjects:
  - secretName: visign-secrets
    type: Opaque
    data:
    - objectName: DATABASE-URL
      key: DATABASE_URL
    - objectName: CLERK-PUBLISHABLE-KEY
      key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    - objectName: CLERK-SECRET-KEY
      key: CLERK_SECRET_KEY
    - objectName: OPENAI-API-KEY
      key: OPENAI_API_KEY
    - objectName: TORCH-COMPUTE
      key: TORCH_COMPUTE