apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: SecretProviderClass
      name: visign-kv-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: 858c6c89-9082-4fdb-a689-df348debe518
      - op: replace
        path: /spec/parameters/keyvaultName
        value: visign-nonprod-kv-zse7xf

  - target:
      kind: Ingress
      name: visign-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.lyhua.dpdns.org
      - op: replace
        path: /spec/tls/0/secretName
        value: visign-tls-dev
      - op: replace
        path: /spec/rules/0/host
        value: dev.lyhua.dpdns.org
