apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visign-dev
resources:
  - ../base
  - secrets-provider.yaml
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: visign-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: remove
        path: /spec/template/spec/topologySpreadConstraints
  - target:
      kind: Deployment
      name: visign-ai
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: remove
        path: /spec/template/spec/topologySpreadConstraints
images:
  - name: visign-ai
    newName: visigndacrftll4r7kkywwy.azurecr.io/visign-ai
    newTag: "dev-d7b74d9d71a0da09f77a6b8cc1fe95856c364dc7"
  - name: visign-web
    newName: visignnonprodacrzse7xf.azurecr.io/visign-web
    newTag: "dev-2389e22b5dedc7d1788387872428b5a0fc9d83b8"
