apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visign-dev
resources:
  - ../base
  - secrets-provider.yaml
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: visign-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: remove
        path: /spec/template/spec/topologySpreadConstraints
  - target:
      kind: Deployment
      name: visign-ai
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: remove
        path: /spec/template/spec/topologySpreadConstraints
images:
  - name: visign-ai
    newName: visignnonprodacrzse7xf.azurecr.io/visign-ai
    newTag: "dev-27e73cc3b5f75a6c57199ada9d4a4b816ba1195a"
  - name: visign-web
    newName: visignnonprodacrzse7xf.azurecr.io/visign-web
    newTag: "dev-613bdfe70b3e22358fb98fb9ad4ab257601183f8"
