apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: visign-prod

commonLabels:
  app.kubernetes.io/name: visign-web
  app.kubernetes.io/instance: prod
  app.kubernetes.io/component: web

resources:
  - ../../../base
  - ../shared/namespace.yaml

patches:
  - path: ../shared/secrets-provider.yaml
  - path: ../shared/ingress.yaml
  - target:
      kind: Deployment
      name: visign-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: visign-web

images:
  - name: visign-web
    newName: visignpacrftll4r7kkywwy.azurecr.io/visign-web
    newTag: "prod-latest"
  - name: visign-web-migrator
    newName: visignpacrftll4r7kkywwy.azurecr.io/visign-web-migrator
    newTag: "prod-latest"
