- target:
    kind: Ingress
    name: visign-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: prod.lyhua.dpdns.org
    - op: replace
      path: /spec/tls/0/secretName
      value: visign-tls-prod
    - op: replace
      path: /spec/rules/0/host
      value: prod.lyhua.dpdns.org
