apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: visign
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployments/visign-web.yaml
  - deployments/visign-ai.yaml
  - services/visign-web.yaml
  - services/visign-ai.yaml
  - jobs/db-migration.yaml
  - ingress.yaml
  - secrets-provider.yaml

images:
  - name: visign-ai
    newTag: ""
  - name: visign-web
    newTag: ""
