apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: visign-dev

commonLabels:
  app.kubernetes.io/name: visign-ai
  app.kubernetes.io/instance: dev
  app.kubernetes.io/component: ai

resources:
  - ../../../base
  - ../shared/namespace.yaml

patches:
  - path: ../shared/secrets-provider.yaml
  - path: ../shared/ingress.yaml
  - target:
      kind: Deployment
      name: visign-ai
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: visign-ai
    newName: visignnonprodacrzse7xf.azurecr.io/visign-ai
    newTag: "dev-latest"
