apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: visign-tls
  namespace: visign
spec:
  secretName: visign-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - lyhua.dpdns.org